### ISSUE TITLE
'localizedStatusCode' is undefined

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#1394]
I got notified of an App Engine error:

```
jinja2.exceptions.UndefinedError
'localizedStatusCode' is undefined
getitem
Service: default
Version: 20201009t172025
```

@bazzadp could you look into this?

**Comment by bazzadp** [comment]
Don’t suppose it told you which URL caused this error?

**Comment by rviscomi** [comment]
I don't see a way to get the URL but from the looks of the stack trace it seems to have happened on the 404 page, or a similar error page.

```
Traceback (most recent call last):
  File "/layers/google.python.pip/pip/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/flask/app.py", line 1816, in handle_user_exception
    return self.handle_http_exception(e)
  File "/layers/google.python.pip/pip/flask/app.py", line 1744, in handle_http_exception
    return handler(e)
  File "/srv/server/errors.py", line 22, in page_not_found
    return render_error_template(error=e, status_code=404)
  File "/srv/server/helpers.py", line 60, in render_error_template
    return render_template('%s/%s/error.html' % (lang, year), lang=lang, year=year, error=error), status_code
  File "/srv/server/helpers.py", line 47, in render_template
    return flask_render_template(template, *args, **kwargs)
  File "/layers/google.python.pip/pip/flask/templating.py", line 137, in render_template
    return _render(
  File "/layers/google.python.pip/pip/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/layers/google.python.pip/pip/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/srv/server/../templates/base/2019/error.html", line 1, in top-level template code
    {% extends "%s/2019/base.html" % lang %}
  File "/srv/server/../templates/base/2019/base.html", line 596, in top-level template code
    <a href="{{ url_for('home', lang=lang,year=y) }}">{{ y }} {{ self.home() }}</a>
  File "/srv/server/../templates/base.html", line 6, in top-level template code
    {% block head %}
  File "/srv/server/../templates/base.html", line 7, in block "head"
    <title>{% block title %}The Web Almanac{% endblock %}</title>
  File "/srv/server/../templates/base/2019/error.html", line 4, in block "title"
    {% block error %}
  File "/srv/server/../templates/base/2019/error.html", line 5, in block "error"
    {{ localizedStatusCode[error.code] if localizedStatusCode[error.code]|length else self.unknown_error() }}
  File "/layers/google.python.pip/pip/jinja2/environment.py", line 452, in getitem
    return obj[argument]
jinja2.exceptions.UndefinedError: 'localizedStatusCode' is undefined
```
