### ISSUE TITLE
Charts failing to load

### ISSUE THREAD

**Issue by tunetheweb** [HTTPArchive/almanac.httparchive.org#3803]
The Google Sheets embeds are failing to load with the following errors:

```
Uncaught ReferenceError: ritz_tviz_charts is not defined
    at pubchart?oid=304563360&amp;format=interactive:1:16543Understand this errorAI
2739753093-ChartsExportJ2cl_j2cl_core.js:538

Uncaught TypeError: Cannot read properties of undefined (reading 'CALL_CHART_LEGEND_MORE_ENTRIES')
    at aO (2739753093-ChartsExportJ2cl_j2cl_core.js:683:216)
    at CM.na (2739753093-ChartsExportJ2cl_j2cl_core.js:1522:461)
    at $ta (2739753093-ChartsExportJ2cl_j2cl_core.js:541:6)
    at DT (2739753093-ChartsExportJ2cl_j2cl_core.js:538:35)
    at r.vo (2739753093-ChartsExportJ2cl_j2cl_core.js:1732:393)
    at U8.V (2739753093-ChartsExportJ2cl_j2cl_core.js:1932:925)
    at drawChartComponent (pubchart?oid=304563360&amp;format=interactive:1:15067)
    at drawRitzChart (pubchart?oid=304563360&amp;format=interactive:1:12975)
    at initCharts (pubchart?oid=304563360&amp;format=interactive:1:12325)
    at onChartsExportApiLoad (pubchart?oid=304563360&amp;format=interactive:1:16505)
```

Raised a bug with Sheets team.

Example to test if fixed: https://docs.google.com/spreadsheets/d/e/2PACX-1vTsnJP1ulTTc-j9n7CIbGHxO1SaFvmZWMPQnJHrluku254CqKXz_D2fn2Ck54FC-m9135eCFg83NHOc/pubchart?oid=109625269&format=interactive

**Comment by tunetheweb** [comment]
Looks like this is finally fixed. Reverting this now...
