### ISSUE TITLE
Chapter validation error

### ISSUE THREAD

**Issue by rviscomi** [HTTPArchive/almanac.httparchive.org#719]
Getting these errors in the server logs:

```
Traceback (most recent call last):
  File "/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/validate.py", line 33, in decorated_function
    validated_chapter = validate_chapter(chapter,year)
  File "/srv/validate.py", line 54, in validate_chapter
    if chapter not in chapters_for_year:
TypeError: argument of type 'NoneType' is not iterable"
```

It's saying `chapters_for_year` is None. This is a new variable added by #712. @bazzadp could you take a look at this?

**Comment by bazzadp** [comment]
Looks like this happens because we try to validate the chapter before the year.

Only called for chapters so /en/2020/methodology correctly 404s as it has a higher precedence route, whereas /en/2020/http2 bombs out.

Fixed in #720
